### ISSUE TITLE
Storage Charts 2 almost triples request time even on reads

### ISSUE THREAD

**Issue by XANi** [hypery2k/owncloud#356] opened 2015-11-04 13:30 UTC
OC 8.1.1 SC 2.6.1

Enabling storage charts makes simple requets like downloading image for preview work 3x-4x as slow, looking at strace it looks like it tries to recalculate on every **read**
##

**Comment by mckaygerhard** [comment] 2015-11-06 21:05
well this project currently are stalled but u can paste here the log and point the trace that u xpected are the issue

of course there-s a line code that paste in log when this operation will be performed.. as "..running in owncloud ..."

**Comment by mckaygerhard** [comment] 2015-11-23 13:38
i retest that into OC 7 and OC 6 and theres no problem (i'm using OC and SC since 2013 and no problems), **as i said, the real problem its change the thinks that already works..**

i any body have a code that solve the situation **please made a pull request and will be analized, tested and merged, of course, backguard compatibility must be!**

**Comment by bugsyb** [comment] 2016-01-05 11:34
I have the very same issue. With Storage Charts 2 enabled WebUI is extremely slow. At the same time WebDAV access seems to be not impacted that much (if at all).

**Comment by mckaygerhard** [comment] 2016-01-29 16:27
@bugsyb please could u report what version of OC are using and php, also server. please without that we cannot help, i'm using OC 7 with SC2 and works perfect!

**Comment by bugsyb** [comment] 2016-01-29 23:43
@mckaygerhard I'm using Version ownCloud 8.2.2 (stable)

**Comment by mckaygerhard** [comment] 2016-02-02 13:48
@bugsyb oficial supported version are the optimized such 6.X and 7.X, in 8.X.X (with X.X >>  1.9) OC have lower performance rather than older OC versions.. 

takin in consideration this, SC make some extra calls to mantain up to date the available space respect user storage and king of user that makes those calls, so its obvius that are more slower with those newer versions..

please can u provide me logs, but in this behavior:
1) login to OC with SC enabled and no more plugins, go tho the images places (not at file, use image icon aside left) and stop at this point (no more actions
2) just after, delete the log file (assuming the install at /var/www/html) the file its called owncloud.log at the data directory
3) then make one only requets a refresh and then copycat the log file with no more actions

called this log file "owncloud1.log" and then repeat the process but now with a request in file (not image icon, just inside file directory of images) but inside the directory of images where are stored
called this second file "owncloud2.log"

then paste here (PLEASE FORMATED WITH MARKDOWN) or attach here (github issues support attached files)

**i cannot guarantee support for OC 8.X due i prefered OC <<< 8 and php 5.3 due performance are much better so far away!!** but i try to find something..

**Comment by hypery2k** [comment] 2016-03-09 05:25
it should be possible to use hooks to overcome this issue

**Comment by mckaygerhard** [comment] 2016-03-14 18:23
hooks its the right, but means hard/close development and i all ready know, i not have enought time to implemented..  and the development of the plugins here are staled.. inclusivelly, currently i not have scheduled make anything in RC or OC until july where i'll make some work to support my two production OC (i used oc 7 and oc 6 and works perfect)

**Comment by mckaygerhard** [comment] 2016-10-04 01:04
i added the bug label takin in consideration that SC make some extra calls to mantain up to date the available space respect user storage and king of user that makes those calls, so its obvius that are more slower with those newer versions.. 

by the moment if server are not apache and oc version are not >> 8 the performance are not impacted so much

due development are staled patches are free welcome or until some have time to investigate solution to this

**Comment by mckaygerhard** [comment] 2017-02-17 13:20
I'll  concluding thiss stupit isue after reading some pooor performance using the mysql DBMS:

clarify cpu load if used poor engine db as mysql, see similar issues like:
* owncloud/client#331
* owncloud/core#21915
in productin env i used postgresql and no cpu load has noted! loading of main page are faster rather than mysql engine, inclusively using sqlite are more faster!

i see similar problems with nextcloud, also similar behavior if used osticket and mysql.. the engine has some problems of performance

**Closed by mckaygerhard** 2017-02-17 13:20 UTC
Labels: bug, enhancement, storage_charts

**Comment by bugsyb** [comment] 2017-03-09 20:01
Apologies, but I won't be able to move my installation to postgres.

Given the very small size of installation (couple of users with 3-4
active, low number of changes, just high number of untouched files) it
is difficult to agree that this is due to MySQL performance. The host
does not provide any other services and sports 16GB of RAM and plenty of
CPU power.


Regards,
Dawid

**Comment by mckaygerhard** [comment] 2017-03-09 20:25
hi @bugsyb i dont said u must move u'r installation.. i just said that the problem rely on the duple mysql+oc so its not a bug this issue.. 

so then i'm sorry could not help you. its true that staoregechars need some cicles to get stats, but i use postgres and oracle and the bug its'n reproducible in that behaviour, 

so the problem relies in the mysql engine and the charge of may little files, i confirmed that using mysql the problems appears.. so in the future if that issues referenced by oc get some solution i'll try to help on this

**Comment by bugsyb** [comment] 2017-03-09 20:27
Thanks for swift and helpful responses.

I'm sorry I couldn't test it with postgres, the effort required to move
to postgres wouldn't bring the results.


Thanks for help!

**Comment by mckaygerhard** [comment] 2017-03-09 20:27
NEWS: forget to said, i use mariadb 5.3.11 and debian 5 (9 years old) and the problems does not happened... in the oc forums there's more info in similar situations
