### ISSUE TITLE
Failed to log-off from roundcube

### ISSUE THREAD

**Issue by airasim** [hypery2k/owncloud#299] opened 2015-02-02 18:48 UTC
Hello,

Owncloud doesn't logg-off the users from roundcube when logging-off from owncloud. In owncloud-log i get the following error:
Error 	roundcube 	OC_RoundCube_App.class.php->logout(): Failed to log-off admin from roundcube

After logging-off from owncloud roundcube can be connectet via its direct link (https://mydomain.de/roundcube) without logging-in.

Client:Firefox 35.0.1 on  Windows 7 pro; Server: Owncloud 7.0.4, Roundcube 1.0.4, Linux 2.6.32-531.17.1.lve1.2.60.el6.x86_64, Apache-Version 2.2.29, PHP-Version 5.3.29, MySQL-Version 5.6.22, Perl-Version 5.10.1.

Thanks for your help.

**Comment by hypery2k** [comment] 2015-02-03 10:14
can you please enabled debug logging in owncloud and in the roundcube app and post the log here?

**Comment by airasim** [comment] 2015-02-03 22:04
ok, errorlogs are the following (times differ one hour because of ???)

Roundcube:
[03-Feb-2015 22:57:07 +0100]: PHP Error: Error loading template for logout in /public_html/roundcube/program/include/rcmail_output_html.php on line 496 (POST /roundcube/?_task=logout&_action=logout)

Owncloud:
Error 	roundcube 	OC_RoundCube_App.class.php->refresh(): Failed to refresh the RC session. 	2015-02-03T21:59:23+00:00
Error 	roundcube 	OC_RoundCube_App.class.php->logout(): Failed to log-off admin from roundcube 	2015-02-03T21:57:08+00:00

**Comment by hypery2k** [comment] 2015-02-04 11:09
according to the [roundcube forum](https://forum.myroundcube.com/topic/171-idle-timeout-plugin-error-after-upgrade-roundcube-to-104/) this is a roundcube error. This should be fixed in [http://roundcube.net/download/](version 1.0.5)

Please try with this version again. If this is working for you, I will add an appropriate error message

**Comment by airasim** [comment] 2015-02-04 18:58
ok, updated to rc1.0.5, didn't help, same error.
tried with autologin for users - also didn't help.
additionally controlled the old logs - the problem seems to be new since update to oc7.0.4 and rc1.0.4.
could you add an error message to roundcube developers?

**Comment by hypery2k** [comment] 2015-02-05 13:31
I tried with roundcube 1.0.5 and cannot reproduce you're error:
```
1.2.3.4 - - [05/Feb/2015:14:30:24 +0100] "POST /oc_testing/mysql/roundcube/ HTTP/1.0" 200 5417 "-" "-"
1.2.3.4 - - [05/Feb/2015:14:30:24 +0100] "GET /oc_testing/mysql/roundcube/ HTTP/1.0" 200 5208 "-" "-"
87.253.171.220 - - [05/Feb/2015:14:30:24 +0100] "GET /oc_testing/mysql/owncloud/index.php?logout=true&requesttoken=eca8e88eabe31ca49b80 HTTP/1.1" 302 2029 "http://test.domain.de/oc_testing/mysql/owncloud/index.php/apps/roundcube" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_2) AppleWebKit/600.3.18 (KHTML, like Gecko) Version/8.0.3 Safari/600.3.18"
87.253.171.220 - - [05/Feb/2015:14:30:25 +0100] "GET /oc_testing/mysql/owncloud/index.php HTTP/1.1" 200 2547 "http://test.domain.de/oc_testing/mysql/owncloud/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_2) AppleWebKit/600.3.18 (KHTML, like Gecko) Version/8.0.3 Safari/600.3.18"
87.253.171.220 - - [05/Feb/2015:14:30:25 +0100] "GET /oc_testing/mysql/owncloud/index.php/core/js/oc.js?v=decc2e06a44e61f12a030bc4951563eb HTTP/1.1" 200 2871 "http://test.domain.de/oc_testing/mysql/owncloud/index.php" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_2) AppleWebKit/600.3.18 (KHTML, like Gecko) Version/8.0.3 Safari/600.3.18"
87.253.171.220 - - [05/Feb/2015:14:30:25 +0100] "POST /oc_testing/mysql/owncloud/index.php/core/ajax/translations.php HTTP/1.1" 200 16277 "http://test.domain.de/oc_testing/mysql/owncloud/index.php" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_2) AppleWebKit/600.3.18 (KHTML, like Gecko) Version/8.0.3 Safari/600.3.18"
87.253.171.220 - - [05/Feb/2015:14:30:25 +0100] "GET /oc_testing/mysql/owncloud/cron.php HTTP/1.1" 200 638 "http://test.domain.de/oc_testing/mysql/owncloud/index.php" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_2) AppleWebKit/600.3.18 (KHTML, like Gecko) Version/8.0.3 Safari/600.3.18"
```

**Comment by hypery2k** [comment] 2015-02-05 13:32
did you check the wiki for the [roundcube settings](https://github.com/hypery2k/owncloud/wiki/Roundcube-OC-Installation-and-usage#roundcube-requeriments)?

**Comment by mckaygerhard** [comment] 2015-02-05 23:06
hello @airasim u'r error are particular to u'r installation.. i suggest to tray a new fresh install in a separate test server and try to reproduce that...

when u see that: note some missing files, and the logout procedure are not complete, this are happening at the RC level application not at the plugin application.. so due that i make a fresh new install, and i could reproduce that error... this error only happen in special environment previously installed..  

so then here http://trac.roundcube.net/ticket/1490257 its a specific related rc issue and not of the plugin oc issue.. so then i'll close the issue as invalid and remove the bug mark .. of couerse 

so due some files necesary for the logout process could not be resolved due  extended CSFR prevention, the logout process could not be completed..

**Closed by mckaygerhard** 2015-02-05 23:06 UTC
Labels: bug, roundcube
