### ISSUE TITLE
Incompatible with desktopsharing in 1.8.x desktop client

### ISSUE THREAD

**Issue by plages** [hypery2k/owncloud#329] opened 2015-05-20 09:02 UTC
Hi,

I was testing the sharing functionality of the 1.8.1 client. This worked fine until a certain moment.
Upon clicking "Share with ownCloud" the dialog appears but all controls except  the Close button are missing and the dialogshows the following error:
![clienterror](https://cloud.githubusercontent.com/assets/3436731/7722321/4616f4e4-fedf-11e4-8b08-743032cbe487.png)

A quick look at the server logs showed that this had someting to do with the server configuration.
As i knew i had recently installed the Storage Charts app and i saw errors pointing towards this app, i disabled it. After that the desktop sharing functionality worked perfectly..

**Comment by mckaygerhard** [comment] 2015-05-20 14:35
This issue are related to desktop client app, not the rouncube integration app.. so please read carefully the repo description before paste and report issues!

maybe u must go to: https://github.com/owncloud/client

**Comment by plages** [comment] 2015-05-21 07:32
Well,
Sorry for that. But this was just a matter of mistakenly clicking the wrong repo (roundcube in stead of Storage charts 2)This should be in https://github.com/hypery2k/owncloud/tree/master/storagecharts2  NOT in https://github.com/owncloud/client.

Sorry for the inconvinience i'll repost in the correct place.

**Comment by mckaygerhard** [comment] 2015-05-21 14:51
the issue its about storagecharts? .. i read carefully its seeem a problem in the client?

please explain more the problem. maybe dont understand very well..

**Comment by plages** [comment] 2015-05-21 15:02
The Storage Charts app works well on its own and so does the desktop client.
However as soon as i install the Storage Charts app the Desktop client generates errors that can be traced back to server issues. Also the server logs showed a lot of errors related to the Storage Charts app. Apparently the Storage Charts app causes some kind of config change to the server that conflicts with the desktop client. As you can see in:
https://github.com/owncloud/client/issues/3138 
It seemed useful to notify you

**Comment by mckaygerhard** [comment] 2015-05-21 19:02
hi @plages in the log that u refer i could find any error related to storage charts only in comments u made later..

i use only linux, those errors are guindows only, use debian a real os and then report here, sorry so i'll close the issue if @hypery2k are agree

´´´
04-22 12:00:22:259 0x5998390 unknown: Failed to resolve EGL function eglGetPlatformDisplayEXT (Kan opgegeven procedure niet vinden.)
04-22 12:00:22:260 0x5998390 unknown: static QWindowsEGLStaticContext* QWindowsEGLStaticContext::create(): Could not initialize EGL display: error 0x3001

04-22 12:00:22:260 0x5998390 unknown: static QWindowsEGLStaticContext* QWindowsEGLStaticContext::create(): When using ANGLE, check if d3dcompiler_4x.dll is available
04-22 12:00:22:911 0x5998390 OCC::ConnectionValidator::checkAuthentication: # Check whether authenticated propfind works.
04-22 12:00:22:914 0x5998390 OCC::AbstractNetworkJob::start: !!! OCC::PropfindJob created for QUrl( "https://kloud.kraaijvanger.nl" ) querying "/"
04-22 12:00:26:318 0x5998390 OCC::AbstractNetworkJob::start: !!! OCC::CheckQuotaJob created for QUrl( "https://kloud.kraaijvanger.nl" ) querying "/"
´´´

**Comment by plages** [comment] 2015-05-21 20:18
From the logs shown the ownCloud devs concluded this was a server issue. Further inspection of the logs showed errors related to Storage Charts. After disabling the SC app, the client (which was unchanged) started working perfectly once again.
about your "real OS" comment:
I have ownCloud running on Ubuntu server. And i don't care much for this kind of childish "my Os is better" nonsense. Sorry to be so direct about it. But i just don't think contributes very much to a constructive, problem solving atmosphere.



Sent from smartphone


-------- Oorspronkelijk bericht --------
Van: PICCORO Lenz McKAY <notifications@github.com>
Datum: 21-05-2015 21:02 (GMT+01:00)
Aan: hypery2k/owncloud <owncloud@noreply.github.com>
Cc: Philip Lages | Kraaijvanger Architecten <PhilipLages@kraaijvanger.nl>
Onderwerp: Re: [owncloud] Incompatible with desktopsharing in 1.8.x desktop client (#329)


hi @plages<https://github.com/plages> in the log that u refer i could find any error related to storage charts only in comments u made later..

i use only linux, those errors are guindows only, use debian a real os and then report here, sorry so i'll close the issue if @hypery2k<https://github.com/hypery2k> are agree

´´´
04-22 12:00:22:259 0x5998390 unknown: Failed to resolve EGL function eglGetPlatformDisplayEXT (Kan opgegeven procedure niet vinden.)
04-22 12:00:22:260 0x5998390 unknown: static QWindowsEGLStaticContext* QWindowsEGLStaticContext::create(): Could not initialize EGL display: error 0x3001

04-22 12:00:22:260 0x5998390 unknown: static QWindowsEGLStaticContext* QWindowsEGLStaticContext::create(): When using ANGLE, check if d3dcompiler_4x.dll is available
04-22 12:00:22:911 0x5998390 OCC::ConnectionValidator::checkAuthentication: # Check whether authenticated propfind works.
04-22 12:00:22:914 0x5998390 OCC::AbstractNetworkJob::start: !!! OCC::PropfindJob created for QUrl( "https://kloud.kraaijvanger.nl" ) querying "/"
04-22 12:00:26:318 0x5998390 OCC::AbstractNetworkJob::start: !!! OCC::CheckQuotaJob created for QUrl( "https://kloud.kraaijvanger.nl" ) querying "/"
´´´

**Comment by mckaygerhard** [comment] 2015-05-21 20:24
well its becose i cant found any track of the problem.. the log dont show some tips and i have linux with the client and no errors, so its then a problem in comunication between the gui client (see the log errors) and the server (winbuntu)

please could u provide a more detailed (debug on) log from the server and i can search for something

**Comment by plages** [comment] 2015-05-21 20:34
I understand.
I will try to reproduce the issue/logs next week.  (Out of office until tuesday)



Verzonden vanaf smartphone


-------- Oorspronkelijk bericht --------
Van: PICCORO Lenz McKAY <notifications@github.com>
Datum: 21-05-2015 22:25 (GMT+01:00)
Aan: hypery2k/owncloud <owncloud@noreply.github.com>
Cc: Philip Lages | Kraaijvanger Architecten <PhilipLages@kraaijvanger.nl>
Onderwerp: Re: [owncloud] Incompatible with desktopsharing in 1.8.x desktop client (#329)


well its becose i cant found any track of the problem.. the log dont show some tips and i have linux with the client and no errors, so its then a problem in comunication between the gui client (see the log errors) and the server (winbuntu)

please could u provide a more detailed (debug on) log from the server and i can search for something

�

**Comment by hypery2k** [comment] 2015-05-21 21:03
I'm on vacation. Will try to check it in 2 weeks

**Comment by hypery2k** [comment] 2015-05-31 09:18
please provide the logs which show the suggested server side error. Otherwise it's impossible to get any further ...

**Comment by mckaygerhard** [comment] 2015-05-31 16:21
i'll try some test but cannot reproduce the error that he said.. so we must waith until @plages provide some debbuging logs...

**Comment by mckaygerhard** [comment] 2015-05-31 16:21
due i'm think that its a guindose error, due in linux with oc clien  not got any problems

**Comment by wastingoctober** [comment] 2015-06-01 23:00
I also receive this error. Here is what I see in the ssl_error_log file whenever I attempt to share a file from the desktop client:

PHP Fatal error:  Call to a member function free_space() on boolean in /var/www/html/owncloud/apps/storagecharts2/appinfo/app.php on line 58

**Comment by plages** [comment] 2015-06-02 05:51
Hey Martin,

I will provide the logs this week.
sorry for the delay



Verzonden vanaf smartphone


-------- Oorspronkelijk bericht --------
Van: Martin Reinhardt <notifications@github.com>
Datum: 31-05-2015 11:18 (GMT+01:00)
Aan: hypery2k/owncloud <owncloud@noreply.github.com>
Cc: Philip Lages | Kraaijvanger Architecten <PhilipLages@kraaijvanger.nl>
Onderwerp: Re: [owncloud] Incompatible with desktopsharing in 1.8.x desktop client (#329)


please provide the logs which show the suggested server side error. Otherwise it's impossible to get any further ...

�

**Comment by plages** [comment] 2015-06-03 07:33
So here is an excerpt from theowncloud.log file. I enabled the app, tried to create a share both on Windows and OSX and both genereted an error. I then disabled the app tried again and all was well.

![logfiles](https://cloud.githubusercontent.com/assets/3436731/7954858/93269e3e-09d3-11e5-8416-7043b5c72fca.png)

![ocs error mac](https://cloud.githubusercontent.com/assets/3436731/7954860/98fe3100-09d3-11e5-951c-eef276eaabee.png)

**Comment by mckaygerhard** [comment] 2015-06-03 20:56
i ***noted*** that i'm not used oc 8 and my client are 1.7 on linux.. so **i suspect** that in *newer versions of oc* server and client theres something changes .. 

due are working perfectly and more faster rather than oc 8.X.Y and in my desktop i not have lasted qt4 environment (are very slower) i never update my installations.. (currently i made support myselft)

**so then due that reasons if any have some patched or workarounds post feedback here..**

**Comment by plages** [comment] 2015-06-04 07:28
Well i'm not using OC 8 either. but the client is version 1.8.1. 
What i don't understand is that in earlier comments you stated that you had no errors on your side. Now you state that you run client version 1.7. However this topic is about errors while using desktop sharing functionality. Which isn't even available in the 1.7 branch.

**Comment by mckaygerhard** [comment] 2015-06-04 14:21
yes i not have desktop sharing.. so i cannot have errors.. ;-) so that's why i never see the errors..

u said have oc 7 but with desktop client 1.8.1, umm, u tried with desktop client 1.7.1? (noted that when u use 1.7.1 this will try to upgrade to 1.8)

please can u tried with 1.8.1 client and post feedback?

**Comment by plages** [comment] 2015-06-04 14:23
I can't try with 1.7.X because the error shows when i use desktop sharing which is NOT available in 1.7.x

**Comment by mckaygerhard** [comment] 2015-06-04 14:31
ok.. i see, when u used any other function of 1.8.1 except desktop sharing, works as espected.. and when used 1.8.1 get errors, please we need also the client debug log not only the server log debug ..

**Comment by plages** [comment] 2015-06-04 14:39
Do you mean the client debug log?



Verzonden vanaf smartphone


-------- Oorspronkelijk bericht --------
Van: PICCORO Lenz McKAY <notifications@github.com>
Datum: 04-06-2015 16:31 (GMT+01:00)
Aan: hypery2k/owncloud <owncloud@noreply.github.com>
Cc: Philip Lages | Kraaijvanger Architecten <PhilipLages@kraaijvanger.nl>
Onderwerp: Re: [owncloud] Incompatible with desktopsharing in 1.8.x desktop client (#329)


ok.. i see, when u used any other function of 1.8.1 except desktop sharing, works as espected.. and when used 1.8.1 get errors, please we need also the client debug log not only the server log debug ..

�

**Comment by mckaygerhard** [comment] 2015-06-05 16:53
i dont understand.. u commit a condition if method exist
but i search by myseflt and in OC api the method must be here: 

http://api.owncloud.org/classes/OCP.Files.Storage.html#free_space

so the problem must be in the client!

**Comment by mckaygerhard** [comment] 2015-07-29 21:33
Whoops! I had already complained of the condition, as #347 i think there's a problem in the oc code... i'll made some test with debug enabled due maybe there are a I/O performance dead when the log are written

**Comment by hypery2k** [comment] 2015-08-23 16:04
still issues on that?

**Comment by mckaygerhard** [comment] 2015-08-24 14:15
NO!, but i let open due this are not a storagechart2 bug!, there issues with the oc api, i let a log line code in this commit in the storagechart to see performance due i suspect some strange behabior with this "rare" calls that are non-exits .. see #347

i think that the oc pai have some buggy errors.

**Closed** 2016-06-05 12:04 UTC
Labels: bug, storage_charts
