### ISSUE TITLE
Share links not working when enabled for specific groups

### ISSUE THREAD

**Issue by skywalker666** [hypery2k/owncloud#352] opened 2015-09-15 13:00 UTC
When the plugin is enabled only for specific groups, share links don't work anymore. You still get the layout, but with empty content. Nothing specific seems to be logged. More information can be provided if needed. Enabling the plugin for all users works as desired.
##

**Comment by mckaygerhard** [comment] 2015-09-16 05:01
hi, please which plugin, and please, can enable debbugin and provide log backtrace with detailed info of environment.. thanks in advance

**Comment by hypery2k** [comment] 2015-09-20 12:59
can you please post any logs when specific groups are enabled?

can you please retry the latest nightly build?

https://martinreinhardt-online.de/jenkins/job/OwnCloud_nightly/

**Comment by skywalker666** [comment] 2015-09-21 07:51
Okay, the app ist roundcube. Unfortunately even with debugging turned on, nothing is logged. To reproduce the problem:

1. Enable plugin roundcube for selected groups
2. Open any public share link (in another browser)
3. The file list stays empty, Layout is shown. The button to switch to the gallery does not work and the link contains something like undefined.

When I disable the plugin, or enable for all users everything works as expected. I tried the latest nightly build which has the same behavior.

**Comment by skywalker666** [comment] 2015-09-21 07:53
Here is my list of installed plugins:

Enabled:
 - activity: 2.0.2
 - audios: 1.2.5
 - bookmarks: 0.4
 - calendar: 0.7.3
 - contacts: 0.4.0.0
 - documents: 0.10.2
 - files: 1.1.10
 - files_external: 0.2.3
 - files_mv: 0.8.1a
 - files_pdfviewer: 0.7
 - files_sharing: 0.6.2
 - files_texteditor: 0.4
 - files_trashbin: 0.6.3
 - files_versions: 1.0.6
 - files_videoviewer: 0.1.3
 - galleryplus: 13.0.0
 - ownnote: 1.05
 - sharelinks: 1.0.1
 - tasks: 0.8
 - templateeditor: 0.1
 - updater: 0.6
 - user_ldap: 0.6.1
Disabled:
 - encryption
 - external
 - files_encryption
 - files_locking
 - firstrunwizard
 - gallery
 - provisioning_api
 - roundcube
 - user_external
 - user_webdavauth

Current owncloud version 8.1.3 on CentOS 7 with php-5.4.16-36.el7_1.x86_64 .

**Comment by mckaygerhard** [comment] 2015-09-21 14:50
i'll indicate how to made some usefully info in u'r setup (i do not test due i'm not used oc 8 neithet 7)

in a clean install with only oc and rc related plugins, using chrome << 38 (chrome 40+ has cache problems):
1) go to oc and enable debug log level or more verbose
2) restart all services
3) enable php debug log
4) rm -rf data/owncloud.log
5) activate plugin rc
6) follow the steps to reproduce
7) WHEN ERROR APPEARS DO NOT CLICK ANY ONTHER LINK, hit F12 
8) copy and feedback console error (last tab
9) go to the server and copy all contect of data/owncloud.log and post feedback

please when post the feedback post with format inside "´" as markdown to email can process and hyper2k can view too

**Comment by hypery2k** [comment] 2015-10-02 12:47
I've got no idea why this is happening

**Comment by mckaygerhard** [comment] 2015-11-23 13:42
this are happening only whot the new api, due many calls to private functions.. since OC 8.1 developers started to deprecated some calls making privates and then in OC 8.2 making deprecated. Now many apps in oc store are unusable...
Ok good for OC developers made some organizations on code, but just now! uff. Its too late for that!

**Comment by mckaygerhard** [comment] 2017-06-25 12:55
close this due OC 8 changes too many things, need too recent PHP version and are very slower.. 

i cannot reproduce in OC 7 that works perfectly

**Closed by mckaygerhard** 2017-06-25 12:55 UTC
Labels: bug, roundcube
