### ISSUE TITLE
Redirection loop in Owncloud 8

### ISSUE THREAD

**Issue by bfbones** [hypery2k/owncloud#301] opened 2015-02-11 21:39 UTC
Hello,

Upgrading a well running OC7 installation to OC8 the webmail-link ends in a redirection loop.
In the debug log is just:
Debug	no app in context	Accessing the API class is deprecated! Use the appropriate services instead!

The redirection loops from /index.php/apps/roundcube to /index.php/apps/roundcube.

Any idea how to workaround or fix?
Already tried to disable all "Location: " header-commands in app-libs, no success.

Thanks.

**Comment by hypery2k** [comment] 2015-02-12 06:51
didn't tried OC8 yet, but maybe anyone else tried it.
It's annoying that with each OC version the API changes. That's one of the two reasons I stuff developing this app...

**Comment by diablotin84** [comment] 2015-02-12 13:51
Hello,

i have the same bug, the webmail-link redirect loop on files apps.
Thks for help.

**Comment by hypery2k** [comment] 2015-02-12 16:54
the login itself is working:
```
{"reqId":"d8baef30aaa784966ce5a2e071901d71","remoteAddr":"12.34.56.78","app":"roundcube","message":"RoundcubeLogin.class.php: NOT LOGGED IN: \\n Detected that we're NOT logged in.","level":0,"time":"2015-02-12T16:48:59+00:00","method":"POST","url":"\/oc_testing\/mysql\/owncloud\/index.php"}
{"reqId":"d8baef30aaa784966ce5a2e071901d71","remoteAddr":"12.34.56.78","app":"roundcube","message":"OC_RoundCube_App.class.php->logout(): positive@test.org successfully logged off from roundcube ","level":1,"time":"2015-02-12T16:48:59+00:00","method":"POST","url":"\/oc_testing\/mysql\/owncloud\/index.php"}
{"reqId":"d8baef30aaa784966ce5a2e071901d71","remoteAddr":"12.34.56.78","app":"roundcube","message":"Logout of user positive@test.org from roundcube done","level":1,"time":"2015-02-12T16:48:59+00:00","method":"POST","url":"\/oc_testing\/mysql\/owncloud\/index.php"}
{"reqId":"d8baef30aaa784966ce5a2e071901d71","remoteAddr":"12.34.56.78","app":"roundcube","message":"RoundcubeLogin.class.php: pre_construct: \\n Used Parameters:","level":0,"time":"2015-02-12T16:48:59+00:00","method":"POST","url":"\/oc_testing\/mysql\/owncloud\/index.php"}
{"reqId":"d8baef30aaa784966ce5a2e071901d71","remoteAddr":"12.34.56.78","app":"roundcube","message":"RoundcubeLogin.class.php: pre_construct: \\n webmailHost: test.domain.org","level":0,"time":"2015-02-12T16:48:59+00:00","method":"POST","url":"\/oc_testing\/mysql\/owncloud\/index.php"}
{"reqId":"d8baef30aaa784966ce5a2e071901d71","remoteAddr":"12.34.56.78","app":"roundcube","message":"RoundcubeLogin.class.php: pre_construct: \\n webmailPort: ","level":0,"time":"2015-02-12T16:48:59+00:00","method":"POST","url":"\/oc_testing\/mysql\/owncloud\/index.php"}
{"reqId":"d8baef30aaa784966ce5a2e071901d71","remoteAddr":"12.34.56.78","app":"roundcube","message":"RoundcubeLogin.class.php: pre_construct: \\n webmailPath: \/oc_testing\/mysql\/roundcube\/","level":0,"time":"2015-02-12T16:48:59+00:00","method":"POST","url":"\/oc_testing\/mysql\/owncloud\/index.php"}
{"reqId":"d8baef30aaa784966ce5a2e071901d71","remoteAddr":"12.34.56.78","app":"roundcube","message":"RoundcubeLogin.class.php: pre_construct: \\n enableDebug: 1","level":0,"time":"2015-02-12T16:48:59+00:00","method":"POST","url":"\/oc_testing\/mysql\/owncloud\/index.php"}
{"reqId":"d8baef30aaa784966ce5a2e071901d71","remoteAddr":"12.34.56.78","app":"roundcube","message":"RoundcubeLogin.class.php: __construct: \\n Creating new RoundCubeLogin instance:","level":0,"time":"2015-02-12T16:48:59+00:00","method":"POST","url":"\/oc_testing\/mysql\/owncloud\/index.php"}
{"reqId":"d8baef30aaa784966ce5a2e071901d71","remoteAddr":"12.34.56.78","app":"roundcube","message":"RoundcubeLogin.class.php: post_construct: \\n Created new RoundCubeLogin instance:","level":0,"time":"2015-02-12T16:48:59+00:00","method":"POST","url":"\/oc_testing\/mysql\/owncloud\/index.php"}
{"reqId":"d8baef30aaa784966ce5a2e071901d71","remoteAddr":"12.34.56.78","app":"roundcube","message":"RoundcubeLogin.class.php: post_construct: \\n rcHost: test.domain.org","level":0,"time":"2015-02-12T16:48:59+00:00","method":"POST","url":"\/oc_testing\/mysql\/owncloud\/index.php"}
{"reqId":"d8baef30aaa784966ce5a2e071901d71","remoteAddr":"12.34.56.78","app":"roundcube","message":"RoundcubeLogin.class.php: post_construct: \\n rcPort: ","level":0,"time":"2015-02-12T16:48:59+00:00","method":"POST","url":"\/oc_testing\/mysql\/owncloud\/index.php"}
{"reqId":"d8baef30aaa784966ce5a2e071901d71","remoteAddr":"12.34.56.78","app":"roundcube","message":"RoundcubeLogin.class.php: post_construct: \\n rcPath: \/oc_testing\/mysql\/roundcube\/","level":0,"time":"2015-02-12T16:48:59+00:00","method":"POST","url":"\/oc_testing\/mysql\/owncloud\/index.php"}
{"reqId":"d8baef30aaa784966ce5a2e071901d71","remoteAddr":"12.34.56.78","app":"roundcube","message":"RoundcubeLogin.class.php: login(): : \\n user: positive@test.org","level":0,"time":"2015-02-12T16:48:59+00:00","method":"POST","url":"\/oc_testing\/mysql\/owncloud\/index.php"}
{"reqId":"d8baef30aaa784966ce5a2e071901d71","remoteAddr":"12.34.56.78","app":"roundcube","message":"RoundcubeLogin.class.php: login(): : \\n pass: 42","level":0,"time":"2015-02-12T16:48:59+00:00","method":"POST","url":"\/oc_testing\/mysql\/owncloud\/index.php"}
{"reqId":"d8baef30aaa784966ce5a2e071901d71","remoteAddr":"12.34.56.78","app":"roundcube","message":"RoundcubeLogin.class.php: sendRequest: \\n Trying to connect via \"GET\" to URL \"http:\/\/test.domain.org\/oc_testing\/mysql\/roundcube\/\" on host\"test.domain.org\"","level":0,"time":"2015-02-12T16:48:59+00:00","method":"POST","url":"\/oc_testing\/mysql\/owncloud\/index.php"}
{"reqId":"d8baef30aaa784966ce5a2e071901d71","remoteAddr":"12.34.56.78","app":"roundcube","message":"RoundcubeLogin.class.php: openUrlConnection: \\n Opening URL (url:http:\/\/test.domain.org\/oc_testing\/mysql\/roundcube\/).","level":0,"time":"2015-02-12T16:48:59+00:00","method":"POST","url":"\/oc_testing\/mysql\/owncloud\/index.php"}
{"reqId":"d8baef30aaa784966ce5a2e071901d71","remoteAddr":"12.34.56.78","app":"roundcube","message":"RoundcubeLogin.class.php: NOT LOGGED IN: \\n Detected that we're NOT logged in.","level":0,"time":"2015-02-12T16:48:59+00:00","method":"POST","url":"\/oc_testing\/mysql\/owncloud\/index.php"}
{"reqId":"d8baef30aaa784966ce5a2e071901d71","remoteAddr":"12.34.56.78","app":"roundcube","message":"RoundcubeLogin.class.php: sendRequest: \\n Trying to connect via \"POST\" to URL \"http:\/\/test.domain.org\/oc_testing\/mysql\/roundcube\/\" on host\"test.domain.org\"","level":0,"time":"2015-02-12T16:48:59+00:00","method":"POST","url":"\/oc_testing\/mysql\/owncloud\/index.php"}
{"reqId":"d8baef30aaa784966ce5a2e071901d71","remoteAddr":"12.34.56.78","app":"roundcube","message":"RoundcubeLogin.class.php: openUrlConnection: \\n Opening URL (url:http:\/\/test.domain.org\/oc_testing\/mysql\/roundcube\/).","level":0,"time":"2015-02-12T16:48:59+00:00","method":"POST","url":"\/oc_testing\/mysql\/owncloud\/index.php"}
{"reqId":"d8baef30aaa784966ce5a2e071901d71","remoteAddr":"12.34.56.78","app":"roundcube","message":"RoundcubeLogin.class.php: sendRequest: \\n New session auth: '-del-'.","level":0,"time":"2015-02-12T16:48:59+00:00","method":"POST","url":"\/oc_testing\/mysql\/owncloud\/index.php"}
{"reqId":"d8baef30aaa784966ce5a2e071901d71","remoteAddr":"12.34.56.78","app":"roundcube","message":"RoundcubeLogin.class.php: sendRequest: \\n Got the following session ID shjlp10r2dkp17hudi3vb22v32","level":0,"time":"2015-02-12T16:48:59+00:00","method":"POST","url":"\/oc_testing\/mysql\/owncloud\/index.php"}
{"reqId":"d8baef30aaa784966ce5a2e071901d71","remoteAddr":"12.34.56.78","app":"roundcube","message":"RoundcubeLogin.class.php: sendRequest: \\n New session auth: 'S256327ddc72f647b1690c69108bb4d58d5073969'.","level":0,"time":"2015-02-12T16:48:59+00:00","method":"POST","url":"\/oc_testing\/mysql\/owncloud\/index.php"}
{"reqId":"d8baef30aaa784966ce5a2e071901d71","remoteAddr":"12.34.56.78","app":"roundcube","message":"RoundcubeLogin.class.php: LOGIN SUCCESSFUL: \\n RC sent a redirection to .\/?_task=..., that means we did it!","level":0,"time":"2015-02-12T16:48:59+00:00","method":"POST","url":"\/oc_testing\/mysql\/owncloud\/index.php"}
{"reqId":"d8baef30aaa784966ce5a2e071901d71","remoteAddr":"12.34.56.78","app":"roundcube","message":"OC_RoundCube_App.class.php->login(): Trying to log into roundcube webinterface under \/oc_testing\/mysql\/roundcube\/ as user positive@test.org","level":0,"time":"2015-02-12T16:48:59+00:00","method":"POST","url":"\/oc_testing\/mysql\/owncloud\/index.php"}
{"reqId":"d8baef30aaa784966ce5a2e071901d71","remoteAddr":"12.34.56.78","app":"roundcube","message":"OC_RoundCube_App.class.php->login(): positive@test.org already logged into roundcube ","level":0,"time":"2015-02-12T16:48:59+00:00","method":"POST","url":"\/oc_testing\/mysql\/owncloud\/index.php"}

```

I've got no idea why it redirects. Also the admin-settings are not working, as the security model in OC8 eight was changed. I will not further investigate on this. Don't have time for this and the app was discontinued

**Comment by owncloud84** [comment] 2015-02-12 20:34
Hey, adding the following lines to routes.php seems to fix the roundcube-app:

$this->create('roundcube_index', '/')->action(
    function($params){
        require __DIR__ . '/../index.php';
    }
);

I will do some further tests but it looks quite well ;-)

cu.

**Comment by hypery2k** [comment] 2015-02-12 20:57
thanks for the suggestion, i will give it a try:

https://martinreinhardt-online.de/jenkins/job/OwnCloud_integration_tests/

**Comment by hypery2k** [comment] 2015-02-12 21:57
seems to work so far with OC8

**Comment by bfbones** [comment] 2015-02-12 23:07
confirming, just running as before.
It seems that the settings are saved, but there is no response to the user.

**Comment by hypery2k** [comment] 2015-02-13 07:37
if you try to change the settings, the previous settings are returned ...

**Comment by mckaygerhard** [comment] 2015-02-13 19:50
> "It's annoying that with each OC version the API changes. That's one of the two reasons I stuff developing this app..."

i agree!

**Comment by hypery2k** [comment] 2015-02-13 20:12
so the app seems to work so far, but the settings of the app look a little bit weird in the new UI and besides that the saving of new settings is not working. So if anybody finds out why feel free to push in with a pull request. 
I personally stick to use OwnCloud 7

**Comment by jayalpes** [comment] 2015-02-14 11:17
same probleme with the UI, impossible to save the roundcube settings (like the path) in the administration or the profile in "RoundCube Mailaccount" (email and pasword) ...
OC 8.0.0.7 and roundcube apps version 2.5.4

**Comment by hypery2k** [comment] 2015-02-14 11:38
and the issue won't be fixed as the app is discontinued

**Comment by mckaygerhard** [comment] 2015-02-14 21:37
since oc are sponsored by and enterprise, there's a race to a always use newest, introducing changes to made incompatible the olders versions, this forces clients to the newer and upgrades and so then company can request money on each new version..

there's a sick of "the newest", the latest version does not bring new things you really need, the only one that really is new useful is only useful for companies that use windows, (now office documents is published also online)

**Comment by diablotin84** [comment] 2015-02-16 10:09
Hi,
Thks for return, unfortunately not working for me.
I have error "PHP Fatal error: Allowed Memory Size of [...]  in
/var/www/owncloud/3rdparty/symfony/routing/Symfony/Component/Routing/Matcher/UrlMatcher.php
on line 96" when i click on the appslink

Sincerely,

**Comment by hypery2k** [comment] 2015-02-16 10:44
@diablotin84: this has nothing to do with the app itself. you're using to less PHP memory

increase you're PHP memory limit in /etc/php/php.ini, /etc/php4/php.ini, /etc/php4/php.ini or/etc/php/apache2/php.ini (depends on your setup)

If there were previously something like that:
```
memory_limit = 160M ; Maximum amount of memory a script may consume
```
Increase the number
```
memory_limit = 200M ; Maximum amount of memory a script may consume
```
and restart your web server

**Comment by diablotin84** [comment] 2015-02-16 11:01
Thks for return!

already done, the problem remains the same



2015-02-16 11:44 GMT+01:00 Martin Reinhardt <notifications@github.com>:

**Comment by hypery2k** [comment] 2015-02-16 11:04
but it's no software problem, it's an configuration problem. Seems that the new owncloud needs more memory for all the new features...

**Comment by diablotin84** [comment] 2015-02-16 11:51
The PHP fatal error is caused by this error: Use of undefined constant DIR
- assumed 'DIR' at /var/www/owncloud/apps/roundcube/appinfo/routes.php

2015-02-16 12:04 GMT+01:00 Martin Reinhardt <notifications@github.com>:

**Comment by hypery2k** [comment] 2015-02-16 12:44
but you didn't posted this log error ;)
So which version are you using? One of the nightly builds or a custom patched version?

Because in the repo (https://github.com/hypery2k/owncloud/blob/master/roundcube/src/main/php/appinfo/routes.php) is now DIR variable ;)

**Comment by hypery2k** [comment] 2015-02-16 12:46
so please use always the nightly builds https://martinreinhardt-online.de/jenkins/job/OwnCloud_nightly/ as mentioned on the github page and report then errors, not with handcrafted versions...

**Comment by diablotin84** [comment] 2015-02-16 13:10
I use a version available in a owncloud repo for debian.

http://download.opensuse.org/repositories/isv:/ownCloud:/community/Debian_7.0/

2015-02-16 13:46 GMT+01:00 Martin Reinhardt <notifications@github.com>:

**Comment by hypery2k** [comment] 2015-02-16 13:23
sorry i mean the roundcube app

**Comment by hypery2k** [comment] 2015-02-16 13:24
but the app packaged there has errors, please use one of the nightly

**Comment by diablotin84** [comment] 2015-02-16 15:24
problem solved.

For install via repo

Replace or Add:

$this->create('roundcube_index', '/')->action(
function($params){
require DIR.'/../index.php';
}
);

By

$this->create('roundcube_index', '/')->action(
function($params){
require '/var/www/owncloud/apps/roundcube/index.php';
}
);

Thks for help.

2015-02-16 14:24 GMT+01:00 Martin Reinhardt <notifications@github.com>:

**Comment by hypery2k** [comment] 2015-02-17 20:23
Manual login not working in OC8

**Closed** 2015-02-19 06:35 UTC
Labels: bug, wontfix
