### ISSUE TITLE
Problem saving mail account settings

### ISSUE THREAD

**Issue by actomas** [hypery2k/owncloud#333] opened 2015-06-05 13:31 UTC
When a save the settings form users mail account in personal section, i can access to webmail with no problems, but when i close the session in own cloud and entry again webmail section say to me that i must put again mail account settings, so data is save on the database but it cannot catch it.

**Comment by mckaygerhard** [comment] 2015-06-05 16:45
please provide the debug enabled logs and details of instalations, remenber that without it we can made so much!

**Comment by vadimkim** [comment] 2015-06-09 09:10
I have the same issue with fresh install of OC 8 and latest Roundcube.  Where to look for debug log?

**Comment by mckaygerhard** [comment] 2015-06-09 20:19
goes to the owncloud admin part and at the end choose the log level to the lowes (debuggin i think, consult the owncloud help docs)

then copy and paste the results from fresh install  (again goes to the owncloud devel docs help)

i do that, ssh to the server and then in the oc dir data files erase the log file, and refresh page of oc url, and then the log file recreates and copy the contents with cat to a html file and see throught the browser..

**Comment by vadimkim** [comment] 2015-06-10 06:51
I got the log. It is pretty big.... The only problem I see right now is: 
{"reqId":"44a719df70a3456590a455fa0a4c47f0","remoteAddr":"x.x.x.x","app":"roundcube","message":"RoundcubeLogin.class.php: openUrlConnection: \\n Got the following HTTP Status Code: (0) SSL certificate problem: unable to get local issuer certificate","level":0,"time":"2015-06-10T06:44:57+00:00","method":"POST","url":"\/index.php\/apps\/roundcube\/ajax\/userSettings.php"}
{"reqId":"44a719df70a3456590a455fa0a4c47f0","remoteAddr":"x.x.x.x","app":"roundcube","message":"RoundcubeLogin.class.php: openUrlConnection: \\n Opening url https:\/\/webmail.ant.ee\/ failed with SSL certificate problem: unable to get local issuer certificate","level":3,"time":"2015-06-10T06:44:57+00:00","method":"POST","url":"\/index.php\/apps\/roundcube\/ajax\/userSettings.php"}

What function does it use to verify SSL?  Or this is not a verification problem? I use StartSSL cert, so it should be trusted.

**Comment by mckaygerhard** [comment] 2015-06-10 14:15
in the wiki there are process when url are ouside of the domain.. 

seems that the url for the roundcube of u'r environment are different from the owncloud .. so for that cases there's a extra steps in the wiki, please see and verify here: https://github.com/hypery2k/owncloud/wiki/Roundcube-OC-Installation-and-usage#custom-different-server-setup-tips

**Comment by vadimkim** [comment] 2015-06-10 18:48
Roundcube and Owncloud resides on the same host, but served under different document roots indeed. The only "working" configuration is where origin-policy=webmail.ant.ee (not https:// or http:// -- got error resolving hostname http or https) and absolute path=/ because it is appended to origin-policy. I have put "disable SSL verification" and now I don't have error with saving credentials, but my screen shows nothing. It is entirely blank

**Comment by mckaygerhard** [comment] 2015-06-10 22:31
if the screen are now blank ples provide :
1. debug log now (starting from point of the app visit)
2. hit F12 in webbrowser and debug console error if any

and pase here property

**Comment by vadimkim** [comment] 2015-06-15 07:17
Sorry for late reply -- I have re-installed owncloud and application to be sure I didn't miss something.
The frame is still empty, but it seems there is something wrong with "origin". Console at web-browser shows:

Refused to display 'https://webmail.ant.ee/' in a frame because it set 'X-Frame-Options' to 'sameorigin'.
2jquery.min.js:5 Uncaught SecurityError: Failed to read the 'contentDocument' property from 'HTMLIFrameElement': Sandbox access violation: Blocked a frame at "https://cloud.ant.ee" from accessing a frame at "null".  The frame being accessed is sandboxed and lacks the "allow-same-origin" flag.

Everything run on the same server, but 
OC -- https://cloud.ant.ee
Roundcube -- https://webmail.ant.ee

plugin "same-origin policies" -- webmail.ant.ee
plugin "absolute path" -- /

**Comment by mckaygerhard** [comment] 2015-06-15 13:36
umm seems that in newer very newer browsers the x-same-origin option are not sense in the roundcube setting, or do u forget to set that to fasle?.. umm please can u try to find something atha complaint and put in the owncloud or try to revise if u forget that setting.. in the wiki there's a info about it in the requeriments.. do u read it?

**Comment by mckaygerhard** [comment] 2015-06-15 13:58
umm investigating i found that in newer brosers and newer html5 format theres some options like allow-forms and allow-x-same-origins.. i have some problems with this configuration type too.. i'll make some test changes in my production env and post feedback in few hours

**Comment by mckaygerhard** [comment] 2015-06-15 14:18
hello @hypery2k  and @vadimkim , now i made some "ajust" for the rounducbe plugin, addingin the options `allow-forms	` (Re-enables form submission) and `allow-same-origin`	(Allows the iframe content to be treated as being from the same origin) fixed that problems, and i found the real reason of the cause to do not login (well only one of two causes)

1) firts, using the manual login the decryption of the kay username and password from rouncube table get only on error (i cannot found the type of error for now..) and thats why te readon of the app coldunt login, SEEMS that the parse of the user faild when try to decript the user password
2) second using autologin feature, the username and passwodr does not stored in the rounducbe table.. in this case, my mail setting are very specials and i cannot determine real cause, due i not using the complete mail name, only the user mail name and pam sync..

i attached the relevant parts of the log files and later i'll try to made something to find from where are the cause of the error:

```
{"app":"roundcube","message":"OC_RoundCube_AuthHelper.class.php->login(): Starting manual login","level":0,"time":"2015-06-15T14:03:57+00:00"}
{"app":"roundcube","message":"OC_RoundCube_App.class.php->checkLoginData(): Checking login data for oc user mailuser1","level":0,"time":"2015-06-15T14:03:57+00:00"}
{"app":"roundcube","message":"OC_RoundCube_App.class.php->checkLoginData(): Found login data for oc user mailuser1","level":0,"time":"2015-06-15T14:03:57+00:00"}
{"app":"roundcube","message":"OC_RoundCube_App.class.php->decryptMyEntry(): Starting decryption.","level":0,"time":"2015-06-15T14:03:57+00:00"}
{"app":"roundcube","message":"OC_RoundCube_App.class.php->decryptMyEntry(): Decryption finished with errors.","level":3,"time":"2015-06-15T14:03:57+00:00"}
{"app":"roundcube","message":"OC_RoundCube_AuthHelper.class.php->login(): Used roundcube user: ","level":0,"time":"2015-06-15T14:03:57+00:00"}
{"app":"roundcube","message":"OC_RoundCube_App.class.php->decryptMyEntry(): Starting decryption.","level":0,"time":"2015-06-15T14:03:57+00:00"}
{"app":"roundcube","message":"OC_RoundCube_App.class.php->decryptMyEntry(): Decryption finished with errors.","level":3,"time":"2015-06-15T14:03:57+00:00"}
{"app":"roundcube","message":"RoundcubeLogin.class.php: post_construct: \\n Created new RoundCubeLogin instance:","level":0,"time":"2015-06-15T14:03:57+00:00"}
{"app":"roundcube","message":"RoundcubeLogin.class.php: post_construct: \\n rcHost: dominio.net","level":0,"time":"2015-06-15T14:03:57+00:00"}
{"app":"roundcube","message":"RoundcubeLogin.class.php: post_construct: \\n rcPort: ","level":0,"time":"2015-06-15T14:03:57+00:00"}
{"app":"roundcube","message":"RoundcubeLogin.class.php: post_construct: \\n rcPath: \/simplemail\/","level":0,"time":"2015-06-15T14:03:57+00:00"}
{"app":"roundcube","message":"RoundcubeLogin.class.php: pre_construct: \\n enableDebug: on","level":0,"time":"2015-06-15T14:03:57+00:00"}
{"app":"roundcube","message":"RoundcubeLogin.class.php: pre_construct: \\n disableSSLverify: on","level":0,"time":"2015-06-15T14:03:57+00:00"}
{"app":"roundcube","message":"RoundcubeLogin.class.php: login: \\n Logging in with ","level":0,"time":"2015-06-15T14:03:57+00:00"}
{"app":"roundcube","message":"RoundcubeLogin.class.php: sendRequest: \\n Trying to connect via \"GET\" to URL \"http:\/\/dominio.net\/simplemail\/\" on host\"dominio.net\"","level":0,"time":"2015-06-15T14:03:57+00:00"}
{"app":"roundcube","message":"RoundcubeLogin.class.php: openUrlConnection: \\n url: http:\/\/dominio.net\/simplemail\/","level":0,"time":"2015-06-15T14:03:57+00:00"}
{"app":"roundcube","message":"RoundcubeLogin.class.php: openUrlConnection: \\n method: GET","level":0,"time":"2015-06-15T14:03:57+00:00"}
{"app":"roundcube","message":"RoundcubeLogin.class.php: openUrlConnection: \\n cookie: ","level":0,"time":"2015-06-15T14:03:57+00:00"}
{"app":"roundcube","message":"RoundcubeLogin.class.php: openUrlConnection: \\n Disabling SSL verification.","level":0,"time":"2015-06-15T14:03:57+00:00"}
{"app":"roundcube","message":"RoundcubeLogin.class.php: openUrlConnection: \\n Got the following HTTP Status Code: (200) ","level":0,"time":"2015-06-15T14:03:57+00:00"}
{"app":"roundcube","message":"RoundcubeLogin.class.php: sendRequest: \\n Got the following Set-Cookie Value: TRACKID=d21b249ebe824a4f8151604a6c135d6e; Path=\/; Version=1","level":0,"time":"2015-06-15T14:03:57+00:00"}
{"app":"roundcube","message":"RoundcubeLogin.class.php: sendRequest: \\n Got the following Set-Cookie Value: roundcube_sessid=212f106upq05ljc6csbfhmtlk7; path=\/; HttpOnly","level":0,"time":"2015-06-15T14:03:57+00:00"}
{"app":"roundcube","message":"RoundcubeLogin.class.php: sendRequest: \\n Got the following session ID: 212f106upq05ljc6csbfhmtlk7","level":0,"time":"2015-06-15T14:03:57+00:00"}
{"app":"roundcube","message":"RoundcubeLogin.class.php: sendRequest: \\n Got the following Set-Cookie Value: roundcube_sessauth=-del-; expires=Mon, 15-Jun-2015 14:02:57 GMT; path=\/; httponly","level":0,"time":"2015-06-15T14:03:57+00:00"}
{"app":"roundcube","message":"RoundcubeLogin.class.php: sendRequest: \\n Got the following session auth: -del-","level":0,"time":"2015-06-15T14:03:57+00:00"}
{"app":"roundcube","message":"RoundcubeLogin.class.php: sendRequest: \\n Got the following token: d09383bd683a3cf8e509ad2ac2b851bf","level":0,"time":"2015-06-15T14:03:57+00:00"}
```

**Comment by vadimkim** [comment] 2015-06-15 18:45
@mckaygerhard 
I have xframe_restriction => false at my owncloud settings.

**Comment by hypery2k** [comment] 2015-06-16 04:01
still the issue of not saving seems to be not completely removed, see https://martinreinhardt-online.de/jenkins/view/BMP_OwnCloud/job/OwnCloud_test/Webtest_Report/

**Comment by mckaygerhard** [comment] 2015-06-17 17:39
related with #338 as my log reveals:

{"app":"roundcube","message":"OC_RoundCube_App.class.php->decryptMyEntry(): Decryption finished with errors.","level":3,"time":"2015-06-15T14:03:57+00:00"}

**Comment by mckaygerhard** [comment] 2015-06-22 15:34
i tested lasted and now works only with manual account login, with autologin does not work!

**Comment by actomas** [comment] 2015-06-25 12:45
My log reveals:

Error	roundcube	Got the following error code: 10	2015-06-25T12:29:11+00:00
Error	roundcube	Not rendering roundcube iframe view due to errors	2015-06-25T12:29:11+00:00
Error	roundcube	OC_RoundCube_App.class.php->showMailFrame(): RoundCube can not login to roundcube due to a login exception to roundcube	2015-06-25T12:29:11+00:00
Error	roundcube	OC_RoundCube_App.class.php->showMailFrame(): There were login errors	2015-06-25T12:29:11+00:00
Error	roundcube	OC_RoundCube_App.class.php->login(): : RoundCube can't login to roundcube due to a login error to roundcube	2015-06-25T12:29:11+00:00
Error	roundcube	OC_RoundCube_App.class.php->decryptMyEntry(): Decryption finished with errors.	2015-06-25T12:29:10+00:00
Error	roundcube	OC_RoundCube_App.class.php->decryptMyEntry(): Decryption finished with errors.	2015-06-25T12:29:10+00:00

**Comment by hypery2k** [comment] 2015-06-25 14:40
I know, that's why the tests are failing: https://martinreinhardt-online.de/jenkins/view/BMP_OwnCloud/
Currently having not much time for investigation. Currently having not much time, because maintaining all the different setups costs much time and this is just a hobby for me.

Sorry, maybe anybody else wants to pick this up.

**Comment by TerraRick** [comment] 2015-06-29 12:07
I've come to the same conclusion as mckaygerhard commented 7 days ago ....
RC login only works with manual OC account login; with OC autologin it does not work!
Looks like OC does not pass the users password to RC app in case of OC autologin.
I'll see if i have some time this week to investigate  ....

**Comment by mckaygerhard** [comment] 2015-06-29 15:50
@TerraRick rc does pass the pasword, the problem its not passing the info, its that the info its not stored in the table when autologin are used..

i investigate the cause several times ago.. and got the two problems.. but now i unnable to retreive the code solution, the solution its a right decoding of the key and the second solution right savin in the table of users/pass..

i apreciate some help/code due my php limitations....

**Comment by hypery2k** [comment] 2015-06-29 16:23
the maintenance of the different combinations of owncloud and roundcube needs much effort and for me personally I don't have time for this. My current focus is my primary job for earning money as this project currently eats for me more and more time/money. Many people using this plugin/OSS think about this like free beer and I'm not willing to support it anymore. Sorry to say...
Within the next weeks/months I don't see from my side many progress for this issue. If anybody want to push, feel free, any help is appreciated. My tests should ensure that the main version combinations are working. Thats the only think besides providing the test environment with Jenkins to verify this...
Regarding the technical issues, @mckaygerhard is totally right

**Comment by TerraRick** [comment] 2015-07-02 13:18
Update:
The OC_RoundCube_AuthHelper->login() function in RoundCubeAuthHelper.class.php is the only location in the OC RC app where the user login is executed on the RC Webmailclient.
The OC_RoundCube_AuthHelper->login() function is only executed when the event 'OC_User'->'post_login' is emitted by the OC core. (Hooked in app.php)
This event is only launched in case of a manual OC login, the event is not emitted in case of a OC auto login (there we have our problem!)
Now i have the following question ... is this a OC bug, or does OC work as designed?
In case of "works as designed" ... i'm affraid that the RC OC app has to be redesigned; The login has also to be done in another place, and the private key must be encrypted with something other than the users password, because the user password is not available in case of an OC autologin.
Maybe Martin can give us a hint in the right direction ?

**Comment by hypery2k** [comment] 2015-07-02 15:02
thats not correct, if you look in OC_RoundCube_AuthHelper.class.php you see:

![java_-_owncloud_roundcube_src_main_php_lib_roundcubeauthhelper_class_php_-_zend_studio_-__users_mreinhardt_documents_programmierung_workspaces_zend_owncloud](https://cloud.githubusercontent.com/assets/979121/8480085/ff153b04-20db-11e5-89f8-0a10509f5c7b.png)

It's no action that for manual logins the method is not called:

![roundcube_aod](https://cloud.githubusercontent.com/assets/979121/8480086/0152c314-20dc-11e5-8a08-5a7678eb7530.png)

It seems for like a encryption/decryption issue

**Comment by TerraRick** [comment] 2015-07-02 15:44
That's what i figured out too, but, what I was trying to say, is that the "post_login" is only fired from within the "OCP\Util", when the end-user does a manual OC login screen ....
![oc-manual-login](https://cloud.githubusercontent.com/assets/6708160/8480997/3cb6e2f0-20e1-11e5-8b0f-931fcfffca68.jpg)
When the end-user has checked the "remember password" checkbox in the OC login screen, the next time the user starts up his browser, and enters his owncloud URL, the user will be automatically loggin in, and in that case, the  "post_login" is NOT fired from within the "OCP\Util", and the user will not be logged in to the Rouncube API.

**Comment by hypery2k** [comment] 2015-07-02 16:35
yes that's correct but that's a totally different issue ;)

**Comment by TerraRick** [comment] 2015-07-02 17:03
I don't know if this is a different issue other than "actomas" started this issue 27 days ago ... the symptoms are the same ... but anyway, i don't want to start a discussion on this matter ...

Martin, can you give us a hint if this "different issue" is a bug in OC, or a bug in the RoundCube App ?

**Comment by hypery2k** [comment] 2015-07-02 17:37
it's completly different issue, I've created #343

**Comment by TerraRick** [comment] 2015-07-02 17:46
Thnx

**Closed** 2016-01-24 10:19 UTC
Labels: bug, roundcube
